// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesOrderManager.Server.Repositories;

#nullable disable

namespace SalesOrderManager.Server.Migrations
{
    [DbContext(typeof(SalesOrderContext))]
    [Migration("20230209203743_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesOrderManager.Shared.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New York Building 1",
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            Name = "California Hotel AJK",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Models.SubElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("WindowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WindowId");

                    b.ToTable("SubElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Element = 1,
                            Height = 1850,
                            Type = "Doors",
                            Width = 1250,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 2,
                            Element = 2,
                            Height = 1850,
                            Type = "Window",
                            Width = 800,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 3,
                            Element = 3,
                            Height = 1850,
                            Type = "Window",
                            Width = 700,
                            WindowId = 1
                        },
                        new
                        {
                            Id = 4,
                            Element = 1,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 2
                        },
                        new
                        {
                            Id = 5,
                            Element = 1,
                            Height = 2200,
                            Type = "Doors",
                            Width = 1400,
                            WindowId = 3
                        },
                        new
                        {
                            Id = 6,
                            Element = 2,
                            Height = 2200,
                            Type = "Window",
                            Width = 600,
                            WindowId = 3
                        },
                        new
                        {
                            Id = 7,
                            Element = 1,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 4
                        },
                        new
                        {
                            Id = 8,
                            Element = 1,
                            Height = 2000,
                            Type = "Window",
                            Width = 1500,
                            WindowId = 4
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Models.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOfWindows")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubElements")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Windows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A51",
                            OrderId = 1,
                            QuantityOfWindows = 4,
                            TotalSubElements = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "C Zone 5",
                            OrderId = 1,
                            QuantityOfWindows = 2,
                            TotalSubElements = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "GLB",
                            OrderId = 2,
                            QuantityOfWindows = 3,
                            TotalSubElements = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "OHF",
                            OrderId = 2,
                            QuantityOfWindows = 10,
                            TotalSubElements = 2
                        });
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Models.SubElement", b =>
                {
                    b.HasOne("SalesOrderManager.Shared.Models.Window", "Window")
                        .WithMany("SubElements")
                        .HasForeignKey("WindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Window");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Models.Window", b =>
                {
                    b.HasOne("SalesOrderManager.Shared.Models.Order", "Order")
                        .WithMany("Windows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Models.Order", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("SalesOrderManager.Shared.Models.Window", b =>
                {
                    b.Navigation("SubElements");
                });
#pragma warning restore 612, 618
        }
    }
}
